version: '3.8'
services:
  webserver:
    build:
      context: .
      dockerfile: dockerfile
    container_name: webserver-apache
    ports:
      - "80:80"
#    volumes:
#      - "web:/usr/local/apache2/htdocs"
