# -*- mode: ruby -*-
# vi: set ft=ruby :

machines = {
  "master" => {"memory" => "512", "cpu" => "0.5", "ip" => "3", "image" => "alpine:latest"},
  "node01" => {"memory" => "512", "cpu" => "0.5", "ip" => "4", "image" => "alpine:latest"},
  "node02" => {"memory" => "512", "cpu" => "0.5", "ip" => "5", "image" => "alpine:latest"},
  "node03" => {"memory" => "512", "cpu" => "0.5", "ip" => "6", "image" => "alpine:latest"}
}

Vagrant.configure("2") do |config|

	machines.each do |name, conf|
		config.vm.define "#{name}" do |machine|
			machine.vm.box = "#{conf["image"]}"
			machine.vm.hostname = "#{name}"
			machine.vm.network "private_network", ip: "10.10.10.#{conf["ip"]}"
			machine.vc.provider "virtualbox do |vb|
				vb.name = "#{name}"
				vb.memory = conf["memory"]
				vb.cpus = conf["cpu]
			
			end 
			config.vm.provision "shell", path: "docker.sh"

			if "#{name}" == "master"
				config.vm.provision "shell", path: "master.sh"
			else
				config.vm.provision "shell", path: "worker.sh
			end

		end
	end
end
